[
	{ "mask": "+247-####", "cc": "AC", "cd": "Ascension", "desc_en": "", "name_ru": "РћСЃС‚СЂРѕРІ Р’РѕР·РЅРµСЃРµРЅРёСЏ", "desc_ru": "" },
	{ "mask": "+376-###-###", "cc": "AD", "cd": "Andorra", "desc_en": "", "name_ru": "РђРЅРґРѕСЂСЂР°", "desc_ru": "" },
	{ "mask": "+971-5#-###-####", "cc": "AE", "cd": "United Arab Emirates", "desc_en": "mobile", "name_ru": "РћР±СЉРµРґРёРЅРµРЅРЅС‹Рµ РђСЂР°Р±СЃРєРёРµ Р­РјРёСЂР°С‚С‹", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+971-#-###-####", "cc": "AE", "cd": "United Arab Emirates", "desc_en": "", "name_ru": "РћР±СЉРµРґРёРЅРµРЅРЅС‹Рµ РђСЂР°Р±СЃРєРёРµ Р­РјРёСЂР°С‚С‹", "desc_ru": "" },
	{ "mask": "+93-##-###-####", "cc": "AF", "cd": "Afghanistan", "desc_en": "", "name_ru": "РђС„РіР°РЅРёСЃС‚Р°РЅ", "desc_ru": "" },
	{ "mask": "+1(268)###-####", "cc": "AG", "cd": "Antigua & Barbuda", "desc_en": "", "name_ru": "РђРЅС‚РёРіСѓР° Рё Р‘Р°СЂР±СѓРґР°", "desc_ru": "" },
	{ "mask": "+1(264)###-####", "cc": "AI", "cd": "Anguilla", "desc_en": "", "name_ru": "РђРЅРіРёР»СЊСЏ", "desc_ru": "" },
	{ "mask": "+355(###)###-###", "cc": "AL", "cd": "Albania", "desc_en": "", "name_ru": "РђР»Р±Р°РЅРёСЏ", "desc_ru": "" },
	{ "mask": "+374-##-###-###", "cc": "AM", "cd": "Armenia", "desc_en": "", "name_ru": "РђСЂРјРµРЅРёСЏ", "desc_ru": "" },
	{ "mask": "+599-###-####", "cc": "AN", "cd": "Caribbean Netherlands", "desc_en": "", "name_ru": "РљР°СЂРёР±СЃРєРёРµ РќРёРґРµСЂР»Р°РЅРґС‹", "desc_ru": "" },
	{ "mask": "+599-###-####", "cc": "AN", "cd": "Netherlands Antilles", "desc_en": "", "name_ru": "РќРёРґРµСЂР»Р°РЅРґСЃРєРёРµ РђРЅС‚РёР»СЊСЃРєРёРµ РѕСЃС‚СЂРѕРІР°", "desc_ru": "" },
	{ "mask": "+599-9###-####", "cc": "AN", "cd": "Netherlands Antilles", "desc_en": "Curacao", "name_ru": "РќРёРґРµСЂР»Р°РЅРґСЃРєРёРµ РђРЅС‚РёР»СЊСЃРєРёРµ РѕСЃС‚СЂРѕРІР°", "desc_ru": "РљСЋСЂР°СЃР°Рѕ" },
	{ "mask": "+244(###)###-###", "cc": "AO", "cd": "Angola", "desc_en": "", "name_ru": "РђРЅРіРѕР»Р°", "desc_ru": "" },
	{ "mask": "+672-1##-###", "cc": "AQ", "cd": "Australian bases in Antarctica", "desc_en": "", "name_ru": "РђРІСЃС‚СЂР°Р»РёР№СЃРєР°СЏ Р°РЅС‚Р°СЂРєС‚РёС‡РµСЃРєР°СЏ Р±Р°Р·Р°", "desc_ru": "" },
	{ "mask": "+54(###)###-####", "cc": "AR", "cd": "Argentina", "desc_en": "", "name_ru": "РђСЂРіРµРЅС‚РёРЅР°", "desc_ru": "" },
	{ "mask": "+1(684)###-####", "cc": "AS", "cd": "American Samoa", "desc_en": "", "name_ru": "РђРјРµСЂРёРєР°РЅСЃРєРѕРµ РЎР°РјРѕР°", "desc_ru": "" },
	{ "mask": "+43(###)###-####", "cc": "AT", "cd": "Austria", "desc_en": "", "name_ru": "РђРІСЃС‚СЂРёСЏ", "desc_ru": "" },
	{ "mask": "+61-#-####-####", "cc": "AU", "cd": "Australia", "desc_en": "", "name_ru": "РђРІСЃС‚СЂР°Р»РёСЏ", "desc_ru": "" },
	{ "mask": "+297-###-####", "cc": "AW", "cd": "Aruba", "desc_en": "", "name_ru": "РђСЂСѓР±Р°", "desc_ru": "" },
	{ "mask": "+994-##-###-##-##", "cc": "AZ", "cd": "Azerbaijan", "desc_en": "", "name_ru": "РђР·РµСЂР±Р°Р№РґР¶Р°РЅ", "desc_ru": "" },
	{ "mask": "+387-##-#####", "cc": "BA", "cd": "Bosnia and Herzegovina", "desc_en": "", "name_ru": "Р‘РѕСЃРЅРёСЏ Рё Р“РµСЂС†РµРіРѕРІРёРЅР°", "desc_ru": "" },
	{ "mask": "+387-##-####", "cc": "BA", "cd": "Bosnia and Herzegovina", "desc_en": "", "name_ru": "Р‘РѕСЃРЅРёСЏ Рё Р“РµСЂС†РµРіРѕРІРёРЅР°", "desc_ru": "" },
	{ "mask": "+1(246)###-####", "cc": "BB", "cd": "Barbados", "desc_en": "", "name_ru": "Р‘Р°СЂР±Р°РґРѕСЃ", "desc_ru": "" },
	{ "mask": "+880-##-###-###", "cc": "BD", "cd": "Bangladesh", "desc_en": "", "name_ru": "Р‘Р°РЅРіР»Р°РґРµС€", "desc_ru": "" },
	{ "mask": "+32(###)###-###", "cc": "BE", "cd": "Belgium", "desc_en": "", "name_ru": "Р‘РµР»СЊРіРёСЏ", "desc_ru": "" },
	{ "mask": "+226-##-##-####", "cc": "BF", "cd": "Burkina Faso", "desc_en": "", "name_ru": "Р‘СѓСЂРєРёРЅР° Р¤Р°СЃРѕ", "desc_ru": "" },
	{ "mask": "+359(###)###-###", "cc": "BG", "cd": "Bulgaria", "desc_en": "", "name_ru": "Р‘РѕР»РіР°СЂРёСЏ", "desc_ru": "" },
	{ "mask": "+973-####-####", "cc": "BH", "cd": "Bahrain", "desc_en": "", "name_ru": "Р‘Р°С…СЂРµР№РЅ", "desc_ru": "" },
	{ "mask": "+257-##-##-####", "cc": "BI", "cd": "Burundi", "desc_en": "", "name_ru": "Р‘СѓСЂСѓРЅРґРё", "desc_ru": "" },
	{ "mask": "+229-##-##-####", "cc": "BJ", "cd": "Benin", "desc_en": "", "name_ru": "Р‘РµРЅРёРЅ", "desc_ru": "" },
	{ "mask": "+1(441)###-####", "cc": "BM", "cd": "Bermuda", "desc_en": "", "name_ru": "Р‘РµСЂРјСѓРґСЃРєРёРµ РѕСЃС‚СЂРѕРІР°", "desc_ru": "" },
	{ "mask": "+673-###-####", "cc": "BN", "cd": "Brunei Darussalam", "desc_en": "", "name_ru": "Р‘СЂСѓРЅРµР№-Р”Р°СЂСѓСЃСЃР°Р»Р°Рј", "desc_ru": "" },
	{ "mask": "+591-#-###-####", "cc": "BO", "cd": "Bolivia", "desc_en": "", "name_ru": "Р‘РѕР»РёРІРёСЏ", "desc_ru": "" },
	{ "mask": "+55-##-####[#]-####", "cc": "BR", "cd": "Brazil", "desc_en": "", "name_ru": "Р‘СЂР°Р·РёР»РёСЏ", "desc_ru": "" },
	{ "mask": "+1(242)###-####", "cc": "BS", "cd": "Bahamas", "desc_en": "", "name_ru": "Р‘Р°РіР°РјСЃРєРёРµ РћСЃС‚СЂРѕРІР°", "desc_ru": "" },
	{ "mask": "+975-17-###-###", "cc": "BT", "cd": "Bhutan", "desc_en": "", "name_ru": "Р‘СѓС‚Р°РЅ", "desc_ru": "" },
	{ "mask": "+975-#-###-###", "cc": "BT", "cd": "Bhutan", "desc_en": "", "name_ru": "Р‘СѓС‚Р°РЅ", "desc_ru": "" },
	{ "mask": "+267-##-###-###", "cc": "BW", "cd": "Botswana", "desc_en": "", "name_ru": "Р‘РѕС‚СЃРІР°РЅР°", "desc_ru": "" },
	{ "mask": "+375(##)###-##-##", "cc": "BY", "cd": "Belarus", "desc_en": "", "name_ru": "Р‘РµР»Р°СЂСѓСЃСЊ (Р‘РµР»РѕСЂСѓСЃСЃРёСЏ)", "desc_ru": "" },
	{ "mask": "+501-###-####", "cc": "BZ", "cd": "Belize", "desc_en": "", "name_ru": "Р‘РµР»РёР·", "desc_ru": "" },
	{ "mask": "+243(###)###-###", "cc": "CD", "cd": "Dem. Rep. Congo", "desc_en": "", "name_ru": "Р”РµРј. Р РµСЃРї. РљРѕРЅРіРѕ (РљРёРЅС€Р°СЃР°)", "desc_ru": "" },
	{ "mask": "+236-##-##-####", "cc": "CF", "cd": "Central African Republic", "desc_en": "", "name_ru": "Р¦РµРЅС‚СЂР°Р»СЊРЅРѕР°С„СЂРёРєР°РЅСЃРєР°СЏ Р РµСЃРїСѓР±Р»РёРєР°", "desc_ru": "" },
	{ "mask": "+242-##-###-####", "cc": "CG", "cd": "Congo (Brazzaville)", "desc_en": "", "name_ru": "РљРѕРЅРіРѕ (Р‘СЂР°Р·Р·Р°РІРёР»СЊ)", "desc_ru": "" },
	{ "mask": "+41-##-###-####", "cc": "CH", "cd": "Switzerland", "desc_en": "", "name_ru": "РЁРІРµР№С†Р°СЂРёСЏ", "desc_ru": "" },
	{ "mask": "+225-##-###-###", "cc": "CI", "cd": "Cote dвЂ™IvoireВ (Ivory Coast)", "desc_en": "", "name_ru": "РљРѕС‚-РґвЂ™РРІСѓР°СЂ", "desc_ru": "" },
	{ "mask": "+682-##-###", "cc": "CK", "cd": "Cook Islands", "desc_en": "", "name_ru": "РћСЃС‚СЂРѕРІР° РљСѓРєР°", "desc_ru": "" },
	{ "mask": "+56-#-####-####", "cc": "CL", "cd": "Chile", "desc_en": "", "name_ru": "Р§РёР»Рё", "desc_ru": "" },
	{ "mask": "+237-####-####", "cc": "CM", "cd": "Cameroon", "desc_en": "", "name_ru": "РљР°РјРµСЂСѓРЅ", "desc_ru": "" },
	{ "mask": "+86(###)####-####", "cc": "CN", "cd": "China (PRC)", "desc_en": "", "name_ru": "РљРёС‚Р°Р№СЃРєР°СЏ Рќ.Р .", "desc_ru": "" },
	{ "mask": "+86(###)####-###", "cc": "CN", "cd": "China (PRC)", "desc_en": "", "name_ru": "РљРёС‚Р°Р№СЃРєР°СЏ Рќ.Р .", "desc_ru": "" },
	{ "mask": "+86-##-#####-#####", "cc": "CN", "cd": "China (PRC)", "desc_en": "", "name_ru": "РљРёС‚Р°Р№СЃРєР°СЏ Рќ.Р .", "desc_ru": "" },
	{ "mask": "+57(###)###-####", "cc": "CO", "cd": "Colombia", "desc_en": "", "name_ru": "РљРѕР»СѓРјР±РёСЏ", "desc_ru": "" },
	{ "mask": "+506-####-####", "cc": "CR", "cd": "Costa Rica", "desc_en": "", "name_ru": "РљРѕСЃС‚Р°-Р РёРєР°", "desc_ru": "" },
	{ "mask": "+53-#-###-####", "cc": "CU", "cd": "Cuba", "desc_en": "", "name_ru": "РљСѓР±Р°", "desc_ru": "" },
	{ "mask": "+238(###)##-##", "cc": "CV", "cd": "Cape Verde", "desc_en": "", "name_ru": "РљР°Р±Рѕ-Р’РµСЂРґРµ", "desc_ru": "" },
	{ "mask": "+599-###-####", "cc": "CW", "cd": "Curacao", "desc_en": "", "name_ru": "РљСЋСЂР°СЃР°Рѕ", "desc_ru": "" },
	{ "mask": "+357-##-###-###", "cc": "CY", "cd": "Cyprus", "desc_en": "", "name_ru": "РљРёРїСЂ", "desc_ru": "" },
	{ "mask": "+420(###)###-###", "cc": "CZ", "cd": "Czech Republic", "desc_en": "", "name_ru": "Р§РµС…РёСЏ", "desc_ru": "" },
	{ "mask": "+49(####)###-####", "cc": "DE", "cd": "Germany", "desc_en": "", "name_ru": "Р“РµСЂРјР°РЅРёСЏ", "desc_ru": "" },
	{ "mask": "+49(###)###-####", "cc": "DE", "cd": "Germany", "desc_en": "", "name_ru": "Р“РµСЂРјР°РЅРёСЏ", "desc_ru": "" },
	{ "mask": "+49(###)##-####", "cc": "DE", "cd": "Germany", "desc_en": "", "name_ru": "Р“РµСЂРјР°РЅРёСЏ", "desc_ru": "" },
	{ "mask": "+49(###)##-###", "cc": "DE", "cd": "Germany", "desc_en": "", "name_ru": "Р“РµСЂРјР°РЅРёСЏ", "desc_ru": "" },
	{ "mask": "+49(###)##-##", "cc": "DE", "cd": "Germany", "desc_en": "", "name_ru": "Р“РµСЂРјР°РЅРёСЏ", "desc_ru": "" },
	{ "mask": "+49-###-###", "cc": "DE", "cd": "Germany", "desc_en": "", "name_ru": "Р“РµСЂРјР°РЅРёСЏ", "desc_ru": "" },
	{ "mask": "+253-##-##-##-##", "cc": "DJ", "cd": "Djibouti", "desc_en": "", "name_ru": "Р”Р¶РёР±СѓС‚Рё", "desc_ru": "" },
	{ "mask": "+45-##-##-##-##", "cc": "DK", "cd": "Denmark", "desc_en": "", "name_ru": "Р”Р°РЅРёСЏ", "desc_ru": "" },
	{ "mask": "+1(767)###-####", "cc": "DM", "cd": "Dominica", "desc_en": "", "name_ru": "Р”РѕРјРёРЅРёРєР°", "desc_ru": "" },
	{ "mask": "+1(809)###-####", "cc": "DO", "cd": "Dominican Republic", "desc_en": "", "name_ru": "Р”РѕРјРёРЅРёРєР°РЅСЃРєР°СЏ Р РµСЃРїСѓР±Р»РёРєР°", "desc_ru": "" },
	{ "mask": "+1(829)###-####", "cc": "DO", "cd": "Dominican Republic", "desc_en": "", "name_ru": "Р”РѕРјРёРЅРёРєР°РЅСЃРєР°СЏ Р РµСЃРїСѓР±Р»РёРєР°", "desc_ru": "" },
	{ "mask": "+1(849)###-####", "cc": "DO", "cd": "Dominican Republic", "desc_en": "", "name_ru": "Р”РѕРјРёРЅРёРєР°РЅСЃРєР°СЏ Р РµСЃРїСѓР±Р»РёРєР°", "desc_ru": "" },
	{ "mask": "+213-##-###-####", "cc": "DZ", "cd": "Algeria", "desc_en": "", "name_ru": "РђР»Р¶РёСЂ", "desc_ru": "" },
	{ "mask": "+593-##-###-####", "cc": "EC", "cd": "Ecuador ", "desc_en": "mobile", "name_ru": "Р­РєРІР°РґРѕСЂ ", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+593-#-###-####", "cc": "EC", "cd": "Ecuador", "desc_en": "", "name_ru": "Р­РєРІР°РґРѕСЂ", "desc_ru": "" },
	{ "mask": "+372-####-####", "cc": "EE", "cd": "Estonia ", "desc_en": "mobile", "name_ru": "Р­СЃС‚РѕРЅРёСЏ ", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+372-###-####", "cc": "EE", "cd": "Estonia", "desc_en": "", "name_ru": "Р­СЃС‚РѕРЅРёСЏ", "desc_ru": "" },
	{ "mask": "+20(###)###-####", "cc": "EG", "cd": "Egypt", "desc_en": "", "name_ru": "Р•РіРёРїРµС‚", "desc_ru": "" },
	{ "mask": "+291-#-###-###", "cc": "ER", "cd": "Eritrea", "desc_en": "", "name_ru": "Р­СЂРёС‚СЂРµСЏ", "desc_ru": "" },
	{ "mask": "+34(###)###-###", "cc": "ES", "cd": "Spain", "desc_en": "", "name_ru": "РСЃРїР°РЅРёСЏ", "desc_ru": "" },
	{ "mask": "+251-##-###-####", "cc": "ET", "cd": "Ethiopia", "desc_en": "", "name_ru": "Р­С„РёРѕРїРёСЏ", "desc_ru": "" },
	{ "mask": "+358(###)###-##-##", "cc": "FI", "cd": "Finland", "desc_en": "", "name_ru": "Р¤РёРЅР»СЏРЅРґРёСЏ", "desc_ru": "" },
	{ "mask": "+679-##-#####", "cc": "FJ", "cd": "Fiji", "desc_en": "", "name_ru": "Р¤РёРґР¶Рё", "desc_ru": "" },
	{ "mask": "+500-#####", "cc": "FK", "cd": "Falkland Islands", "desc_en": "", "name_ru": "Р¤РѕР»РєР»РµРЅРґСЃРєРёРµ РѕСЃС‚СЂРѕРІР°", "desc_ru": "" },
	{ "mask": "+691-###-####", "cc": "FM", "cd": "F.S. Micronesia", "desc_en": "", "name_ru": "Р¤.РЁ. РњРёРєСЂРѕРЅРµР·РёРё", "desc_ru": "" },
	{ "mask": "+298-###-###", "cc": "FO", "cd": "Faroe Islands", "desc_en": "", "name_ru": "Р¤Р°СЂРµСЂСЃРєРёРµ РѕСЃС‚СЂРѕРІР°", "desc_ru": "" },
	{ "mask": "+262-#####-####", "cc": "FR", "cd": "Mayotte", "desc_en": "", "name_ru": "РњР°Р№РѕС‚С‚Р°", "desc_ru": "" },
	{ "mask": "+33(###)###-###", "cc": "FR", "cd": "France", "desc_en": "", "name_ru": "Р¤СЂР°РЅС†РёСЏ", "desc_ru": "" },
	{ "mask": "+508-##-####", "cc": "FR", "cd": "St Pierre & Miquelon", "desc_en": "", "name_ru": "РЎРµРЅ-РџСЊРµСЂ Рё РњРёРєРµР»РѕРЅ", "desc_ru": "" },
	{ "mask": "+590(###)###-###", "cc": "FR", "cd": "Guadeloupe", "desc_en": "", "name_ru": "Р“РІР°РґРµР»СѓРїР°", "desc_ru": "" },
	{ "mask": "+241-#-##-##-##", "cc": "GA", "cd": "Gabon", "desc_en": "", "name_ru": "Р“Р°Р±РѕРЅ", "desc_ru": "" },
	{ "mask": "+1(473)###-####", "cc": "GD", "cd": "Grenada", "desc_en": "", "name_ru": "Р“СЂРµРЅР°РґР°", "desc_ru": "" },
	{ "mask": "+995(###)###-###", "cc": "GE", "cd": "Rep. of Georgia", "desc_en": "", "name_ru": "Р“СЂСѓР·РёСЏ", "desc_ru": "" },
	{ "mask": "+594-#####-####", "cc": "GF", "cd": "Guiana (French)", "desc_en": "", "name_ru": "Р¤СЂ. Р“РІРёР°РЅР°", "desc_ru": "" },
	{ "mask": "+233(###)###-###", "cc": "GH", "cd": "Ghana", "desc_en": "", "name_ru": "Р“Р°РЅР°", "desc_ru": "" },
	{ "mask": "+350-###-#####", "cc": "GI", "cd": "Gibraltar", "desc_en": "", "name_ru": "Р“РёР±СЂР°Р»С‚Р°СЂ", "desc_ru": "" },
	{ "mask": "+299-##-##-##", "cc": "GL", "cd": "Greenland", "desc_en": "", "name_ru": "Р“СЂРµРЅР»Р°РЅРґРёСЏ", "desc_ru": "" },
	{ "mask": "+220(###)##-##", "cc": "GM", "cd": "Gambia", "desc_en": "", "name_ru": "Р“Р°РјР±РёСЏ", "desc_ru": "" },
	{ "mask": "+224-##-###-###", "cc": "GN", "cd": "Guinea", "desc_en": "", "name_ru": "Р“РІРёРЅРµСЏ", "desc_ru": "" },
	{ "mask": "+240-##-###-####", "cc": "GQ", "cd": "Equatorial Guinea", "desc_en": "", "name_ru": "Р­РєРІР°С‚РѕСЂРёР°Р»СЊРЅР°СЏ Р“РІРёРЅРµСЏ", "desc_ru": "" },
	{ "mask": "+30(###)###-####", "cc": "GR", "cd": "Greece", "desc_en": "", "name_ru": "Р“СЂРµС†РёСЏ", "desc_ru": "" },
	{ "mask": "+502-#-###-####", "cc": "GT", "cd": "Guatemala", "desc_en": "", "name_ru": "Р“РІР°С‚РµРјР°Р»Р°", "desc_ru": "" },
	{ "mask": "+1(671)###-####", "cc": "GU", "cd": "Guam", "desc_en": "", "name_ru": "Р“СѓР°Рј", "desc_ru": "" },
	{ "mask": "+245-#-######", "cc": "GW", "cd": "Guinea-Bissau", "desc_en": "", "name_ru": "Р“РІРёРЅРµСЏ-Р‘РёСЃР°Сѓ", "desc_ru": "" },
	{ "mask": "+592-###-####", "cc": "GY", "cd": "Guyana", "desc_en": "", "name_ru": "Р“Р°Р№Р°РЅР°", "desc_ru": "" },
	{ "mask": "+852-####-####", "cc": "HK", "cd": "Hong Kong", "desc_en": "", "name_ru": "Р“РѕРЅРєРѕРЅРі", "desc_ru": "" },
	{ "mask": "+504-####-####", "cc": "HN", "cd": "Honduras", "desc_en": "", "name_ru": "Р“РѕРЅРґСѓСЂР°СЃ", "desc_ru": "" },
	{ "mask": "+385-##-###-###", "cc": "HR", "cd": "Croatia", "desc_en": "", "name_ru": "РҐРѕСЂРІР°С‚РёСЏ", "desc_ru": "" },
	{ "mask": "+509-##-##-####", "cc": "HT", "cd": "Haiti", "desc_en": "", "name_ru": "Р“Р°РёС‚Рё", "desc_ru": "" },
	{ "mask": "+36(###)###-###", "cc": "HU", "cd": "Hungary", "desc_en": "", "name_ru": "Р’РµРЅРіСЂРёСЏ", "desc_ru": "" },
	{ "mask": "+62(8##)###-####", "cc": "ID", "cd": "Indonesia ", "desc_en": "mobile", "name_ru": "РРЅРґРѕРЅРµР·РёСЏ ", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+62-##-###-##", "cc": "ID", "cd": "Indonesia", "desc_en": "", "name_ru": "РРЅРґРѕРЅРµР·РёСЏ", "desc_ru": "" },
	{ "mask": "+62-##-###-###", "cc": "ID", "cd": "Indonesia", "desc_en": "", "name_ru": "РРЅРґРѕРЅРµР·РёСЏ", "desc_ru": "" },
	{ "mask": "+62-##-###-####", "cc": "ID", "cd": "Indonesia", "desc_en": "", "name_ru": "РРЅРґРѕРЅРµР·РёСЏ", "desc_ru": "" },
	{ "mask": "+62(8##)###-###", "cc": "ID", "cd": "Indonesia ", "desc_en": "mobile", "name_ru": "РРЅРґРѕРЅРµР·РёСЏ ", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+62(8##)###-##-###", "cc": "ID", "cd": "Indonesia ", "desc_en": "mobile", "name_ru": "РРЅРґРѕРЅРµР·РёСЏ ", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+353(###)###-###", "cc": "IE", "cd": "Ireland", "desc_en": "", "name_ru": "РСЂР»Р°РЅРґРёСЏ", "desc_ru": "" },
	{ "mask": "+972-5#-###-####", "cc": "IL", "cd": "Israel ", "desc_en": "mobile", "name_ru": "РР·СЂР°РёР»СЊ ", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+972-#-###-####", "cc": "IL", "cd": "Israel", "desc_en": "", "name_ru": "РР·СЂР°РёР»СЊ", "desc_ru": "" },
	{ "mask": "+91(####)###-###", "cc": "IN", "cd": "India", "desc_en": "", "name_ru": "РРЅРґРёСЏ", "desc_ru": "" },
	{ "mask": "+246-###-####", "cc": "IO", "cd": "Diego Garcia", "desc_en": "", "name_ru": "Р”РёРµРіРѕ-Р“Р°СЂСЃРёСЏ", "desc_ru": "" },
	{ "mask": "+964(###)###-####", "cc": "IQ", "cd": "Iraq", "desc_en": "", "name_ru": "РСЂР°Рє", "desc_ru": "" },
	{ "mask": "+98(###)###-####", "cc": "IR", "cd": "Iran", "desc_en": "", "name_ru": "РСЂР°РЅ", "desc_ru": "" },
	{ "mask": "+354-###-####", "cc": "IS", "cd": "Iceland", "desc_en": "", "name_ru": "РСЃР»Р°РЅРґРёСЏ", "desc_ru": "" },
	{ "mask": "+39(###)####-###", "cc": "IT", "cd": "Italy", "desc_en": "", "name_ru": "РС‚Р°Р»РёСЏ", "desc_ru": "" },
	{ "mask": "+1(876)###-####", "cc": "JM", "cd": "Jamaica", "desc_en": "", "name_ru": "РЇРјР°Р№РєР°", "desc_ru": "" },
	{ "mask": "+962-#-####-####", "cc": "JO", "cd": "Jordan", "desc_en": "", "name_ru": "РРѕСЂРґР°РЅРёСЏ", "desc_ru": "" },
	{ "mask": "+81-##-####-####", "cc": "JP", "cd": "Japan ", "desc_en": "mobile", "name_ru": "РЇРїРѕРЅРёСЏ ", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+81(###)###-###", "cc": "JP", "cd": "Japan", "desc_en": "", "name_ru": "РЇРїРѕРЅРёСЏ", "desc_ru": "" },
	{ "mask": "+254-###-######", "cc": "KE", "cd": "Kenya", "desc_en": "", "name_ru": "РљРµРЅРёСЏ", "desc_ru": "" },
	{ "mask": "+996(###)###-###", "cc": "KG", "cd": "Kyrgyzstan", "desc_en": "", "name_ru": "РљРёСЂРіРёР·РёСЏ", "desc_ru": "" },
	{ "mask": "+855-##-###-###", "cc": "KH", "cd": "Cambodia", "desc_en": "", "name_ru": "РљР°РјР±РѕРґР¶Р°", "desc_ru": "" },
	{ "mask": "+686-##-###", "cc": "KI", "cd": "Kiribati", "desc_en": "", "name_ru": "РљРёСЂРёР±Р°С‚Рё", "desc_ru": "" },
	{ "mask": "+269-##-#####", "cc": "KM", "cd": "Comoros", "desc_en": "", "name_ru": "РљРѕРјРѕСЂС‹", "desc_ru": "" },
	{ "mask": "+1(869)###-####", "cc": "KN", "cd": "Saint Kitts & Nevis", "desc_en": "", "name_ru": "РЎРµРЅС‚-РљРёС‚СЃ Рё РќРµРІРёСЃ", "desc_ru": "" },
	{ "mask": "+850-191-###-####", "cc": "KP", "cd": "DPR Korea (North) ", "desc_en": "mobile", "name_ru": "РљРѕСЂРµР№СЃРєР°СЏ РќР”Р  ", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+850-##-###-###", "cc": "KP", "cd": "DPR Korea (North)", "desc_en": "", "name_ru": "РљРѕСЂРµР№СЃРєР°СЏ РќР”Р ", "desc_ru": "" },
	{ "mask": "+850-###-####-###", "cc": "KP", "cd": "DPR Korea (North)", "desc_en": "", "name_ru": "РљРѕСЂРµР№СЃРєР°СЏ РќР”Р ", "desc_ru": "" },
	{ "mask": "+850-###-###", "cc": "KP", "cd": "DPR Korea (North)", "desc_en": "", "name_ru": "РљРѕСЂРµР№СЃРєР°СЏ РќР”Р ", "desc_ru": "" },
	{ "mask": "+850-####-####", "cc": "KP", "cd": "DPR Korea (North)", "desc_en": "", "name_ru": "РљРѕСЂРµР№СЃРєР°СЏ РќР”Р ", "desc_ru": "" },
	{ "mask": "+850-####-#############", "cc": "KP", "cd": "DPR Korea (North)", "desc_en": "", "name_ru": "РљРѕСЂРµР№СЃРєР°СЏ РќР”Р ", "desc_ru": "" },
	{ "mask": "+82-##-###-####", "cc": "KR", "cd": "Korea (South)", "desc_en": "", "name_ru": "Р РµСЃРї. РљРѕСЂРµСЏ", "desc_ru": "" },
	{ "mask": "+965-####-####", "cc": "KW", "cd": "Kuwait", "desc_en": "", "name_ru": "РљСѓРІРµР№С‚", "desc_ru": "" },
	{ "mask": "+1(345)###-####", "cc": "KY", "cd": "Cayman Islands", "desc_en": "", "name_ru": "РљР°Р№РјР°РЅРѕРІС‹ РѕСЃС‚СЂРѕРІР°", "desc_ru": "" },
	{ "mask": "+7(6##)###-##-##", "cc": "KZ", "cd": "Kazakhstan", "desc_en": "", "name_ru": "РљР°Р·Р°С…СЃС‚Р°РЅ", "desc_ru": "" },
	{ "mask": "+7(7##)###-##-##", "cc": "KZ", "cd": "Kazakhstan", "desc_en": "", "name_ru": "РљР°Р·Р°С…СЃС‚Р°РЅ", "desc_ru": "" },
	{ "mask": "+856(20##)###-###", "cc": "LA", "cd": "Laos ", "desc_en": "mobile", "name_ru": "Р›Р°РѕСЃ ", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+856-##-###-###", "cc": "LA", "cd": "Laos", "desc_en": "", "name_ru": "Р›Р°РѕСЃ", "desc_ru": "" },
	{ "mask": "+961-##-###-###", "cc": "LB", "cd": "Lebanon ", "desc_en": "mobile", "name_ru": "Р›РёРІР°РЅ ", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+961-#-###-###", "cc": "LB", "cd": "Lebanon", "desc_en": "", "name_ru": "Р›РёРІР°РЅ", "desc_ru": "" },
	{ "mask": "+1(758)###-####", "cc": "LC", "cd": "Saint Lucia", "desc_en": "", "name_ru": "РЎРµРЅС‚-Р›СЋСЃРёСЏ", "desc_ru": "" },
	{ "mask": "+423(###)###-####", "cc": "LI", "cd": "Liechtenstein", "desc_en": "", "name_ru": "Р›РёС…С‚РµРЅС€С‚РµР№РЅ", "desc_ru": "" },
	{ "mask": "+94-##-###-####", "cc": "LK", "cd": "Sri Lanka", "desc_en": "", "name_ru": "РЁСЂРё-Р›Р°РЅРєР°", "desc_ru": "" },
	{ "mask": "+231-##-###-###", "cc": "LR", "cd": "Liberia", "desc_en": "", "name_ru": "Р›РёР±РµСЂРёСЏ", "desc_ru": "" },
	{ "mask": "+266-#-###-####", "cc": "LS", "cd": "Lesotho", "desc_en": "", "name_ru": "Р›РµСЃРѕС‚Рѕ", "desc_ru": "" },
	{ "mask": "+370(###)##-###", "cc": "LT", "cd": "Lithuania", "desc_en": "", "name_ru": "Р›РёС‚РІР°", "desc_ru": "" },
	{ "mask": "+352(###)###-###", "cc": "LU", "cd": "Luxembourg", "desc_en": "", "name_ru": "Р›СЋРєСЃРµРјР±СѓСЂРі", "desc_ru": "" },
	{ "mask": "+371-##-###-###", "cc": "LV", "cd": "Latvia", "desc_en": "", "name_ru": "Р›Р°С‚РІРёСЏ", "desc_ru": "" },
	{ "mask": "+218-##-###-###", "cc": "LY", "cd": "Libya", "desc_en": "", "name_ru": "Р›РёРІРёСЏ", "desc_ru": "" },
	{ "mask": "+218-21-###-####", "cc": "LY", "cd": "Libya", "desc_en": "Tripoli", "name_ru": "Р›РёРІРёСЏ", "desc_ru": "РўСЂРёРїРѕР»Рё" },
	{ "mask": "+212-##-####-###", "cc": "MA", "cd": "Morocco", "desc_en": "", "name_ru": "РњР°СЂРѕРєРєРѕ", "desc_ru": "" },
	{ "mask": "+377(###)###-###", "cc": "MC", "cd": "Monaco", "desc_en": "", "name_ru": "РњРѕРЅР°РєРѕ", "desc_ru": "" },
	{ "mask": "+377-##-###-###", "cc": "MC", "cd": "Monaco", "desc_en": "", "name_ru": "РњРѕРЅР°РєРѕ", "desc_ru": "" },
	{ "mask": "+373-####-####", "cc": "MD", "cd": "Moldova", "desc_en": "", "name_ru": "РњРѕР»РґРѕРІР°", "desc_ru": "" },
	{ "mask": "+382-##-###-###", "cc": "ME", "cd": "Montenegro", "desc_en": "", "name_ru": "Р§РµСЂРЅРѕРіРѕСЂРёСЏ", "desc_ru": "" },
	{ "mask": "+261-##-##-#####", "cc": "MG", "cd": "Madagascar", "desc_en": "", "name_ru": "РњР°РґР°РіР°СЃРєР°СЂ", "desc_ru": "" },
	{ "mask": "+692-###-####", "cc": "MH", "cd": "Marshall Islands", "desc_en": "", "name_ru": "РњР°СЂС€Р°Р»Р»РѕРІС‹ РћСЃС‚СЂРѕРІР°", "desc_ru": "" },
	{ "mask": "+389-##-###-###", "cc": "MK", "cd": "Republic of Macedonia", "desc_en": "", "name_ru": "Р РµСЃРї. РњР°РєРµРґРѕРЅРёСЏ", "desc_ru": "" },
	{ "mask": "+223-##-##-####", "cc": "ML", "cd": "Mali", "desc_en": "", "name_ru": "РњР°Р»Рё", "desc_ru": "" },
	{ "mask": "+95-##-###-###", "cc": "MM", "cd": "Burma (Myanmar)", "desc_en": "", "name_ru": "Р‘РёСЂРјР° (РњСЊСЏРЅРјР°)", "desc_ru": "" },
	{ "mask": "+95-#-###-###", "cc": "MM", "cd": "Burma (Myanmar)", "desc_en": "", "name_ru": "Р‘РёСЂРјР° (РњСЊСЏРЅРјР°)", "desc_ru": "" },
	{ "mask": "+95-###-###", "cc": "MM", "cd": "Burma (Myanmar)", "desc_en": "", "name_ru": "Р‘РёСЂРјР° (РњСЊСЏРЅРјР°)", "desc_ru": "" },
	{ "mask": "+976-##-##-####", "cc": "MN", "cd": "Mongolia", "desc_en": "", "name_ru": "РњРѕРЅРіРѕР»РёСЏ", "desc_ru": "" },
	{ "mask": "+853-####-####", "cc": "MO", "cd": "Macau", "desc_en": "", "name_ru": "РњР°РєР°Рѕ", "desc_ru": "" },
	{ "mask": "+1(670)###-####", "cc": "MP", "cd": "Northern Mariana Islands", "desc_en": "", "name_ru": "РЎРµРІРµСЂРЅС‹Рµ РњР°СЂРёР°РЅСЃРєРёРµ РѕСЃС‚СЂРѕРІР°В РЎР°Р№РїР°РЅ", "desc_ru": "" },
	{ "mask": "+596(###)##-##-##", "cc": "MQ", "cd": "Martinique", "desc_en": "", "name_ru": "РњР°СЂС‚РёРЅРёРєР°", "desc_ru": "" },
	{ "mask": "+222-##-##-####", "cc": "MR", "cd": "Mauritania", "desc_en": "", "name_ru": "РњР°РІСЂРёС‚Р°РЅРёСЏ", "desc_ru": "" },
	{ "mask": "+1(664)###-####", "cc": "MS", "cd": "Montserrat", "desc_en": "", "name_ru": "РњРѕРЅС‚СЃРµСЂСЂР°С‚", "desc_ru": "" },
	{ "mask": "+356-####-####", "cc": "MT", "cd": "Malta", "desc_en": "", "name_ru": "РњР°Р»СЊС‚Р°", "desc_ru": "" },
	{ "mask": "+230-###-####", "cc": "MU", "cd": "Mauritius", "desc_en": "", "name_ru": "РњР°РІСЂРёРєРёР№", "desc_ru": "" },
	{ "mask": "+960-###-####", "cc": "MV", "cd": "Maldives", "desc_en": "", "name_ru": "РњР°Р»СЊРґРёРІСЃРєРёРµ РѕСЃС‚СЂРѕРІР°", "desc_ru": "" },
	{ "mask": "+265-1-###-###", "cc": "MW", "cd": "Malawi", "desc_en": "Telecom Ltd", "name_ru": "РњР°Р»Р°РІРё", "desc_ru": "Telecom Ltd" },
	{ "mask": "+265-#-####-####", "cc": "MW", "cd": "Malawi", "desc_en": "", "name_ru": "РњР°Р»Р°РІРё", "desc_ru": "" },
	{ "mask": "+52(###)###-####", "cc": "MX", "cd": "Mexico", "desc_en": "", "name_ru": "РњРµРєСЃРёРєР°", "desc_ru": "" },
	{ "mask": "+52-##-##-####", "cc": "MX", "cd": "Mexico", "desc_en": "", "name_ru": "РњРµРєСЃРёРєР°", "desc_ru": "" },
	{ "mask": "+60-##-###-####", "cc": "MY", "cd": "Malaysia ", "desc_en": "mobile", "name_ru": "РњР°Р»Р°Р№Р·РёСЏ ", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+60(###)###-###", "cc": "MY", "cd": "Malaysia", "desc_en": "", "name_ru": "РњР°Р»Р°Р№Р·РёСЏ", "desc_ru": "" },
	{ "mask": "+60-##-###-###", "cc": "MY", "cd": "Malaysia", "desc_en": "", "name_ru": "РњР°Р»Р°Р№Р·РёСЏ", "desc_ru": "" },
	{ "mask": "+60-#-###-###", "cc": "MY", "cd": "Malaysia", "desc_en": "", "name_ru": "РњР°Р»Р°Р№Р·РёСЏ", "desc_ru": "" },
	{ "mask": "+258-##-###-###", "cc": "MZ", "cd": "Mozambique", "desc_en": "", "name_ru": "РњРѕР·Р°РјР±РёРє", "desc_ru": "" },
	{ "mask": "+264-##-###-####", "cc": "NA", "cd": "Namibia", "desc_en": "", "name_ru": "РќР°РјРёР±РёСЏ", "desc_ru": "" },
	{ "mask": "+687-##-####", "cc": "NC", "cd": "New Caledonia", "desc_en": "", "name_ru": "РќРѕРІР°СЏ РљР°Р»РµРґРѕРЅРёСЏ", "desc_ru": "" },
	{ "mask": "+227-##-##-####", "cc": "NE", "cd": "Niger", "desc_en": "", "name_ru": "РќРёРіРµСЂ", "desc_ru": "" },
	{ "mask": "+672-3##-###", "cc": "NF", "cd": "Norfolk Island", "desc_en": "", "name_ru": "РќРѕСЂС„РѕР»Рє (РѕСЃС‚СЂРѕРІ)", "desc_ru": "" },
	{ "mask": "+234(###)###-####", "cc": "NG", "cd": "Nigeria", "desc_en": "", "name_ru": "РќРёРіРµСЂРёСЏ", "desc_ru": "" },
	{ "mask": "+234-##-###-###", "cc": "NG", "cd": "Nigeria", "desc_en": "", "name_ru": "РќРёРіРµСЂРёСЏ", "desc_ru": "" },
	{ "mask": "+234-##-###-##", "cc": "NG", "cd": "Nigeria", "desc_en": "", "name_ru": "РќРёРіРµСЂРёСЏ", "desc_ru": "" },
	{ "mask": "+234(###)###-####", "cc": "NG", "cd": "Nigeria ", "desc_en": "mobile", "name_ru": "РќРёРіРµСЂРёСЏ ", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+505-####-####", "cc": "NI", "cd": "Nicaragua", "desc_en": "", "name_ru": "РќРёРєР°СЂР°РіСѓР°", "desc_ru": "" },
	{ "mask": "+31-##-###-####", "cc": "NL", "cd": "Netherlands", "desc_en": "", "name_ru": "РќРёРґРµСЂР»Р°РЅРґС‹", "desc_ru": "" },
	{ "mask": "+47(###)##-###", "cc": "NO", "cd": "Norway", "desc_en": "", "name_ru": "РќРѕСЂРІРµРіРёСЏ", "desc_ru": "" },
	{ "mask": "+977-##-###-###", "cc": "NP", "cd": "Nepal", "desc_en": "", "name_ru": "РќРµРїР°Р»", "desc_ru": "" },
	{ "mask": "+674-###-####", "cc": "NR", "cd": "Nauru", "desc_en": "", "name_ru": "РќР°СѓСЂСѓ", "desc_ru": "" },
	{ "mask": "+683-####", "cc": "NU", "cd": "Niue", "desc_en": "", "name_ru": "РќРёСѓСЌ", "desc_ru": "" },
	{ "mask": "+64(###)###-###", "cc": "NZ", "cd": "New Zealand", "desc_en": "", "name_ru": "РќРѕРІР°СЏ Р—РµР»Р°РЅРґРёСЏ", "desc_ru": "" },
	{ "mask": "+64-##-###-###", "cc": "NZ", "cd": "New Zealand", "desc_en": "", "name_ru": "РќРѕРІР°СЏ Р—РµР»Р°РЅРґРёСЏ", "desc_ru": "" },
	{ "mask": "+64(###)###-####", "cc": "NZ", "cd": "New Zealand", "desc_en": "", "name_ru": "РќРѕРІР°СЏ Р—РµР»Р°РЅРґРёСЏ", "desc_ru": "" },
	{ "mask": "+968-##-###-###", "cc": "OM", "cd": "Oman", "desc_en": "", "name_ru": "РћРјР°РЅ", "desc_ru": "" },
	{ "mask": "+507-###-####", "cc": "PA", "cd": "Panama", "desc_en": "", "name_ru": "РџР°РЅР°РјР°", "desc_ru": "" },
	{ "mask": "+51(###)###-###", "cc": "PE", "cd": "Peru", "desc_en": "", "name_ru": "РџРµСЂСѓ", "desc_ru": "" },
	{ "mask": "+689-##-##-##", "cc": "PF", "cd": "French Polynesia", "desc_en": "", "name_ru": "Р¤СЂР°РЅС†СѓР·СЃРєР°СЏ РџРѕР»РёРЅРµР·РёСЏ (РўР°РёС‚Рё)", "desc_ru": "" },
	{ "mask": "+675(###)##-###", "cc": "PG", "cd": "Papua New Guinea", "desc_en": "", "name_ru": "РџР°РїСѓР°-РќРѕРІР°СЏ Р“РІРёРЅРµСЏ", "desc_ru": "" },
	{ "mask": "+63(###)###-####", "cc": "PH", "cd": "Philippines", "desc_en": "", "name_ru": "Р¤РёР»РёРїРїРёРЅС‹", "desc_ru": "" },
	{ "mask": "+92(###)###-####", "cc": "PK", "cd": "Pakistan", "desc_en": "", "name_ru": "РџР°РєРёСЃС‚Р°РЅ", "desc_ru": "" },
	{ "mask": "+48(###)###-###", "cc": "PL", "cd": "Poland", "desc_en": "", "name_ru": "РџРѕР»СЊС€Р°", "desc_ru": "" },
	{ "mask": "+970-##-###-####", "cc": "PS", "cd": "Palestine", "desc_en": "", "name_ru": "РџР°Р»РµСЃС‚РёРЅР°", "desc_ru": "" },
	{ "mask": "+351-##-###-####", "cc": "PT", "cd": "Portugal", "desc_en": "", "name_ru": "РџРѕСЂС‚СѓРіР°Р»РёСЏ", "desc_ru": "" },
	{ "mask": "+680-###-####", "cc": "PW", "cd": "Palau", "desc_en": "", "name_ru": "РџР°Р»Р°Сѓ", "desc_ru": "" },
	{ "mask": "+595(###)###-###", "cc": "PY", "cd": "Paraguay", "desc_en": "", "name_ru": "РџР°СЂР°РіРІР°Р№", "desc_ru": "" },
	{ "mask": "+974-####-####", "cc": "QA", "cd": "Qatar", "desc_en": "", "name_ru": "РљР°С‚Р°СЂ", "desc_ru": "" },
	{ "mask": "+262-#####-####", "cc": "RE", "cd": "Reunion", "desc_en": "", "name_ru": "Р РµСЋРЅСЊРѕРЅ", "desc_ru": "" },
	{ "mask": "+40-##-###-####", "cc": "RO", "cd": "Romania", "desc_en": "", "name_ru": "Р СѓРјС‹РЅРёСЏ", "desc_ru": "" },
	{ "mask": "+381-##-###-####", "cc": "RS", "cd": "Serbia", "desc_en": "", "name_ru": "РЎРµСЂР±РёСЏ", "desc_ru": "" },
	{ "mask": "+7(###)###-##-##", "cc": "RU", "cd": "Russia", "desc_en": "", "name_ru": "Р РѕСЃСЃРёСЏ", "desc_ru": "" },
	{ "mask": "+250(###)###-###", "cc": "RW", "cd": "Rwanda", "desc_en": "", "name_ru": "Р СѓР°РЅРґР°", "desc_ru": "" },
	{ "mask": "+966-5-####-####", "cc": "SA", "cd": "Saudi Arabia ", "desc_en": "mobile", "name_ru": "РЎР°СѓРґРѕРІСЃРєР°СЏ РђСЂР°РІРёСЏ ", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+966-#-###-####", "cc": "SA", "cd": "Saudi Arabia", "desc_en": "", "name_ru": "РЎР°СѓРґРѕРІСЃРєР°СЏ РђСЂР°РІРёСЏ", "desc_ru": "" },
	{ "mask": "+677-###-####", "cc": "SB", "cd": "Solomon Islands ", "desc_en": "mobile", "name_ru": "РЎРѕР»РѕРјРѕРЅРѕРІС‹ РћСЃС‚СЂРѕРІР° ", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+677-#####", "cc": "SB", "cd": "Solomon Islands", "desc_en": "", "name_ru": "РЎРѕР»РѕРјРѕРЅРѕРІС‹ РћСЃС‚СЂРѕРІР°", "desc_ru": "" },
	{ "mask": "+248-#-###-###", "cc": "SC", "cd": "Seychelles", "desc_en": "", "name_ru": "РЎРµР№С€РµР»С‹", "desc_ru": "" },
	{ "mask": "+249-##-###-####", "cc": "SD", "cd": "Sudan", "desc_en": "", "name_ru": "РЎСѓРґР°РЅ", "desc_ru": "" },
	{ "mask": "+46-##-###-####", "cc": "SE", "cd": "Sweden", "desc_en": "", "name_ru": "РЁРІРµС†РёСЏ", "desc_ru": "" },
	{ "mask": "+65-####-####", "cc": "SG", "cd": "Singapore", "desc_en": "", "name_ru": "РЎРёРЅРіР°РїСѓСЂ", "desc_ru": "" },
	{ "mask": "+290-####", "cc": "SH", "cd": "Saint Helena", "desc_en": "", "name_ru": "РћСЃС‚СЂРѕРІ РЎРІСЏС‚РѕР№ Р•Р»РµРЅС‹", "desc_ru": "" },
	{ "mask": "+290-####", "cc": "SH", "cd": "Tristan da Cunha", "desc_en": "", "name_ru": "РўСЂРёСЃС‚Р°РЅ-РґР°-РљСѓРЅСЊСЏ", "desc_ru": "" },
	{ "mask": "+386-##-###-###", "cc": "SI", "cd": "Slovenia", "desc_en": "", "name_ru": "РЎР»РѕРІРµРЅРёСЏ", "desc_ru": "" },
	{ "mask": "+421(###)###-###", "cc": "SK", "cd": "Slovakia", "desc_en": "", "name_ru": "РЎР»РѕРІР°РєРёСЏ", "desc_ru": "" },
	{ "mask": "+232-##-######", "cc": "SL", "cd": "Sierra Leone", "desc_en": "", "name_ru": "РЎСЊРµСЂСЂР°-Р›РµРѕРЅРµ", "desc_ru": "" },
	{ "mask": "+378-####-######", "cc": "SM", "cd": "San Marino", "desc_en": "", "name_ru": "РЎР°РЅ-РњР°СЂРёРЅРѕ", "desc_ru": "" },
	{ "mask": "+221-##-###-####", "cc": "SN", "cd": "Senegal", "desc_en": "", "name_ru": "РЎРµРЅРµРіР°Р»", "desc_ru": "" },
	{ "mask": "+252-##-###-###", "cc": "SO", "cd": "Somalia", "desc_en": "", "name_ru": "РЎРѕРјР°Р»Рё", "desc_ru": "" },
	{ "mask": "+252-#-###-###", "cc": "SO", "cd": "Somalia", "desc_en": "", "name_ru": "РЎРѕРјР°Р»Рё", "desc_ru": "" },
	{ "mask": "+252-#-###-###", "cc": "SO", "cd": "Somalia ", "desc_en": "mobile", "name_ru": "РЎРѕРјР°Р»Рё ", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+597-###-####", "cc": "SR", "cd": "Suriname ", "desc_en": "mobile", "name_ru": "РЎСѓСЂРёРЅР°Рј ", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+597-###-###", "cc": "SR", "cd": "Suriname", "desc_en": "", "name_ru": "РЎСѓСЂРёРЅР°Рј", "desc_ru": "" },
	{ "mask": "+211-##-###-####", "cc": "SS", "cd": "South Sudan", "desc_en": "", "name_ru": "Р®Р¶РЅС‹Р№ РЎСѓРґР°РЅ", "desc_ru": "" },
	{ "mask": "+239-##-#####", "cc": "ST", "cd": "Sao Tome and Principe", "desc_en": "", "name_ru": "РЎР°РЅ-РўРѕРјРµ Рё РџСЂРёРЅСЃРёРїРё", "desc_ru": "" },
	{ "mask": "+503-##-##-####", "cc": "SV", "cd": "El Salvador", "desc_en": "", "name_ru": "РЎР°Р»СЊРІР°РґРѕСЂ", "desc_ru": "" },
	{ "mask": "+1(721)###-####", "cc": "SX", "cd": "Sint Maarten", "desc_en": "", "name_ru": "РЎРёРЅС‚-РњР°Р°СЂС‚РµРЅ", "desc_ru": "" },
	{ "mask": "+963-##-####-###", "cc": "SY", "cd": "Syrian Arab Republic", "desc_en": "", "name_ru": "РЎРёСЂРёР№СЃРєР°СЏ Р°СЂР°Р±СЃРєР°СЏ СЂРµСЃРїСѓР±Р»РёРєР°", "desc_ru": "" },
	{ "mask": "+268-##-##-####", "cc": "SZ", "cd": "Swaziland", "desc_en": "", "name_ru": "РЎРІР°Р·РёР»РµРЅРґ", "desc_ru": "" },
	{ "mask": "+1(649)###-####", "cc": "TC", "cd": "Turks & Caicos", "desc_en": "", "name_ru": "РўС‘СЂРєСЃ Рё РљР°Р№РєРѕСЃ", "desc_ru": "" },
	{ "mask": "+235-##-##-##-##", "cc": "TD", "cd": "Chad", "desc_en": "", "name_ru": "Р§Р°Рґ", "desc_ru": "" },
	{ "mask": "+228-##-###-###", "cc": "TG", "cd": "Togo", "desc_en": "", "name_ru": "РўРѕРіРѕ", "desc_ru": "" },
	{ "mask": "+66-##-###-####", "cc": "TH", "cd": "Thailand ", "desc_en": "mobile", "name_ru": "РўР°РёР»Р°РЅРґ ", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+66-##-###-###", "cc": "TH", "cd": "Thailand", "desc_en": "", "name_ru": "РўР°РёР»Р°РЅРґ", "desc_ru": "" },
	{ "mask": "+992-##-###-####", "cc": "TJ", "cd": "Tajikistan", "desc_en": "", "name_ru": "РўР°РґР¶РёРєРёСЃС‚Р°РЅ", "desc_ru": "" },
	{ "mask": "+690-####", "cc": "TK", "cd": "Tokelau", "desc_en": "", "name_ru": "РўРѕРєРµР»Р°Сѓ", "desc_ru": "" },
	{ "mask": "+670-###-####", "cc": "TL", "cd": "East Timor", "desc_en": "", "name_ru": "Р’РѕСЃС‚РѕС‡РЅС‹Р№ РўРёРјРѕСЂ", "desc_ru": "" },
	{ "mask": "+670-77#-#####", "cc": "TL", "cd": "East Timor", "desc_en": "Timor Telecom", "name_ru": "Р’РѕСЃС‚РѕС‡РЅС‹Р№ РўРёРјРѕСЂ", "desc_ru": "Timor Telecom" },
	{ "mask": "+670-78#-#####", "cc": "TL", "cd": "East Timor", "desc_en": "Timor Telecom", "name_ru": "Р’РѕСЃС‚РѕС‡РЅС‹Р№ РўРёРјРѕСЂ", "desc_ru": "Timor Telecom" },
	{ "mask": "+993-#-###-####", "cc": "TM", "cd": "Turkmenistan", "desc_en": "", "name_ru": "РўСѓСЂРєРјРµРЅРёСЃС‚Р°РЅ", "desc_ru": "" },
	{ "mask": "+216-##-###-###", "cc": "TN", "cd": "Tunisia", "desc_en": "", "name_ru": "РўСѓРЅРёСЃ", "desc_ru": "" },
	{ "mask": "+676-#####", "cc": "TO", "cd": "Tonga", "desc_en": "", "name_ru": "РўРѕРЅРіР°", "desc_ru": "" },
	{ "mask": "+90(###)###-####", "cc": "TR", "cd": "Turkey", "desc_en": "", "name_ru": "РўСѓСЂС†РёСЏ", "desc_ru": "" },
	{ "mask": "+1(868)###-####", "cc": "TT", "cd": "Trinidad & Tobago", "desc_en": "", "name_ru": "РўСЂРёРЅРёРґР°Рґ Рё РўРѕР±Р°РіРѕ", "desc_ru": "" },
	{ "mask": "+688-90####", "cc": "TV", "cd": "Tuvalu ", "desc_en": "mobile", "name_ru": "РўСѓРІР°Р»Сѓ ", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+688-2####", "cc": "TV", "cd": "Tuvalu", "desc_en": "", "name_ru": "РўСѓРІР°Р»Сѓ", "desc_ru": "" },
	{ "mask": "+886-#-####-####", "cc": "TW", "cd": "Taiwan", "desc_en": "", "name_ru": "РўР°Р№РІР°РЅСЊ", "desc_ru": "" },
	{ "mask": "+886-####-####", "cc": "TW", "cd": "Taiwan", "desc_en": "", "name_ru": "РўР°Р№РІР°РЅСЊ", "desc_ru": "" },
	{ "mask": "+255-##-###-####", "cc": "TZ", "cd": "Tanzania", "desc_en": "", "name_ru": "РўР°РЅР·Р°РЅРёСЏ", "desc_ru": "" },
	{ "mask": "+380(##)###-##-##", "cc": "UA", "cd": "Ukraine", "desc_en": "", "name_ru": "РЈРєСЂР°РёРЅР°", "desc_ru": "" },
	{ "mask": "+256(###)###-###", "cc": "UG", "cd": "Uganda", "desc_en": "", "name_ru": "РЈРіР°РЅРґР°", "desc_ru": "" },
	{ "mask": "+44-##-####-####", "cc": "UK", "cd": "United Kingdom", "desc_en": "", "name_ru": "Р’РµР»РёРєРѕР±СЂРёС‚Р°РЅРёСЏ", "desc_ru": "" },
	{ "mask": "+598-#-###-##-##", "cc": "UY", "cd": "Uruguay", "desc_en": "", "name_ru": "РЈСЂСѓРіРІР°Р№", "desc_ru": "" },
	{ "mask": "+998-##-###-####", "cc": "UZ", "cd": "Uzbekistan", "desc_en": "", "name_ru": "РЈР·Р±РµРєРёСЃС‚Р°РЅ", "desc_ru": "" },
	{ "mask": "+39-6-698-#####", "cc": "VA", "cd": "Vatican City", "desc_en": "", "name_ru": "Р’Р°С‚РёРєР°РЅ", "desc_ru": "" },
	{ "mask": "+1(784)###-####", "cc": "VC", "cd": "Saint Vincent & the Grenadines", "desc_en": "", "name_ru": "РЎРµРЅС‚-Р’РёРЅСЃРµРЅС‚ Рё Р“СЂРµРЅР°РґРёРЅС‹", "desc_ru": "" },
	{ "mask": "+58(###)###-####", "cc": "VE", "cd": "Venezuela", "desc_en": "", "name_ru": "Р’РµРЅРµСЃСѓСЌР»Р°", "desc_ru": "" },
	{ "mask": "+1(284)###-####", "cc": "VG", "cd": "British Virgin Islands", "desc_en": "", "name_ru": "Р‘СЂРёС‚Р°РЅСЃРєРёРµ Р’РёСЂРіРёРЅСЃРєРёРµ РѕСЃС‚СЂРѕРІР°", "desc_ru": "" },
	{ "mask": "+1(340)###-####", "cc": "VI", "cd": "US Virgin Islands", "desc_en": "", "name_ru": "РђРјРµСЂРёРєР°РЅСЃРєРёРµ Р’РёСЂРіРёРЅСЃРєРёРµ РѕСЃС‚СЂРѕРІР°", "desc_ru": "" },
	{ "mask": "+84-##-####-###", "cc": "VN", "cd": "Vietnam", "desc_en": "", "name_ru": "Р’СЊРµС‚РЅР°Рј", "desc_ru": "" },
	{ "mask": "+84(###)####-###", "cc": "VN", "cd": "Vietnam", "desc_en": "", "name_ru": "Р’СЊРµС‚РЅР°Рј", "desc_ru": "" },
	{ "mask": "+678-##-#####", "cc": "VU", "cd": "Vanuatu ", "desc_en": "mobile", "name_ru": "Р’Р°РЅСѓР°С‚Сѓ ", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+678-#####", "cc": "VU", "cd": "Vanuatu", "desc_en": "", "name_ru": "Р’Р°РЅСѓР°С‚Сѓ", "desc_ru": "" },
	{ "mask": "+681-##-####", "cc": "WF", "cd": "Wallis and Futuna", "desc_en": "", "name_ru": "РЈРѕР»Р»РёСЃ Рё Р¤СѓС‚СѓРЅР°", "desc_ru": "" },
	{ "mask": "+685-##-####", "cc": "WS", "cd": "Samoa", "desc_en": "", "name_ru": "РЎР°РјРѕР°", "desc_ru": "" },
	{ "mask": "+967-###-###-###", "cc": "YE", "cd": "Yemen ", "desc_en": "mobile", "name_ru": "Р™РµРјРµРЅ ", "desc_ru": "РјРѕР±РёР»СЊРЅС‹Рµ" },
	{ "mask": "+967-#-###-###", "cc": "YE", "cd": "Yemen", "desc_en": "", "name_ru": "Р™РµРјРµРЅ", "desc_ru": "" },
	{ "mask": "+967-##-###-###", "cc": "YE", "cd": "Yemen", "desc_en": "", "name_ru": "Р™РµРјРµРЅ", "desc_ru": "" },
	{ "mask": "+27-##-###-####", "cc": "ZA", "cd": "South Africa", "desc_en": "", "name_ru": "Р®Р¶РЅРѕ-РђС„СЂРёРєР°РЅСЃРєР°СЏ Р РµСЃРї.", "desc_ru": "" },
	{ "mask": "+260-##-###-####", "cc": "ZM", "cd": "Zambia", "desc_en": "", "name_ru": "Р—Р°РјР±РёСЏ", "desc_ru": "" },
	{ "mask": "+263-#-######", "cc": "ZW", "cd": "Zimbabwe", "desc_en": "", "name_ru": "Р—РёРјР±Р°Р±РІРµ", "desc_ru": "" },
	{ "mask": "+1(###)###-####", "cc": ["US", "CA"], "cd": "USA and Canada", "desc_en": "", "name_ru": "РЎРЁРђ Рё РљР°РЅР°РґР°", "desc_ru": "" }
]